// SUNCOM — Système i18n · 6 langues
const SUNCOM_LANGS = {

  fr: {
    nav_cta: "Rejoindre",
    hero_eyebrow: "Mandataires immobiliers & Co-actionnaires",
    hero_sub: "Le futur de l'immobilier s'écrit ici",
    hero_scroll: "Découvrir",
    b1_tag: "Agents & Actionnaires",
    b1_desc: "Mandataire indépendant dans l'immobilier, tu deviens associé & actionnaire ! Tu perçois tes commissions, partages les bénéfices ; tu as un capital réel et un patrimoine transmissible à tout moment.<br><span style=\"color:#ffffff;\">Construis-toi un avenir !</span>",
    b1_link: "Devenir agent fondateur",
    b2_tag: "100% Services Immobiliers",
    b2_desc: "Tes clients ont besoin d'un financement, d'un diagnostic, d'une piscine, d'une extension, d'un paysagiste ? Rejoins nos 52K agents et obtiens ton « <span style=\"font-size:0.85em;\">PASS FACILITIES</span> » pour tes missions avec nos 30K entreprises.<br><span style=\"color:#ffffff;\">Plus de commissions, plus de bénéfices !</span>",
    b2_link: "En savoir plus",
    b3_tag: "Le Club",
    b3_desc: "Échange et partage avec tes confrères et associés au sein de notre club privé. Découvre les derniers outils et les tactiques gagnantes. Consulte tous tes business sur une seule App.<br><span style=\"color:#ffffff;\">Une communauté internationale !</span>",
    b3_link: "Rejoindre le réseau",
    b4_desc: "Participe à la recherche et développement en rejoignant notre Think Tank international à New York. Ici, c'est la tech, l'I.A., les SaaS, la vidéo, la communication, le social network, la veille, les benchmarks… OPEN !<br><span style=\"color:#ffffff;\">Associé avant le 31.08.26 <span style=\"color:#F0A500;\">⌱</span> 1 A/R New York offert depuis ta capitale !</span>",
    b4_link: "Découvrir le Lab",
    footer_rights: "Tous droits réservés",
    // about.html
    about_eyebrow: "⌱ Groupe SUNCOM",
    about_sub: "La structure juridique et financière derrière l'écosystème SUNCOM.",
    e2w_label: "Siège social",
    section_team: "Fondateurs & Associés",
    bio_read: "Lire la biographie",
    bio_hide: "Masquer la biographie",
    erwan_role: "Fondateur & Associé — Président e2w · SUNCOM Associates",
    erwan_b1: "Serial entrepreneur à l'international depuis 1991 — Immobilier & Nouvelles Technologies",
    erwan_b2: "Fondateur et Dirigeant de Sociétés en France, Italie, Espagne, GB, Bahrein...",
    erwan_b3: "Jusqu'à 300 salariés dans le monde — partenariats TV Groupe Canal+ / Air France / Ibéria",
    erwan_history: "Un peu d'histoire",
    erwan_bio: "<p>Né en 1966 et suite à une jeunesse de compétiteur sportif, il a reçu 3 années de formation universitaire en langues et civilisations étrangères avant de comprendre que ce choix d'orientation n'allait pas lui convenir. Il lui fallait de l'action !</p><p>Depuis 35 ans, créateur, dirigeant et actionnaire de sociétés à l'international dans les secteurs de l'immobilier et des nouvelles technologies. En partenariat avec les groupes Canal Plus, Air France et Ibéria, il fut le seul dirigeant à disposer d'un comptoir au nom de sa société aux aéroports de Paris et à posséder son propre avion de ligne pour accompagner sa clientèle sur les sites où étaient déployées ses luxueuses promotions immobilières à travers le monde.</p><p>Dès l'arrivée de l'Internet, sa société MKT Lines comptait parmi les leaders du reverse engineering et de la Search Engine Optimization. D'approche facile et d'un naturel convivial, il partage son temps entre ses activités professionnelles et sportives.</p><p>Il se consacre désormais activement au lancement de son nouveau projet avec la participation de ses associés et amis de longue date, William & Wilfrid. Il pilote et préside e2w et la filiale SUNCOM Associates.</p>",
    william_role: "Fondateur & Associé — Président SUNCOM Facilities",
    william_b1: "Fondateur et gérant depuis 1999 du 1er réseau d'Agents Commerciaux et Freelances",
    william_b2: "Leader depuis 25 ans — 57 000 Agents Commerciaux gérés — 30 000 Entreprises clientes",
    william_b3: "55 milliards d'euros de C.A. générés chaque année par ses équipes",
    william_history: "Un peu d'histoire",
    william_bio: "<p>L'univers de la vente est son moteur ! Né en 1975, diplômé de l'ESC Reims puis de l'EAP Paris-Champernet, il fonde la plateforme AgentCo il y a plus de 25 ans et devient ainsi le N°1 du recrutement et de la mise en relation d'agents commerciaux indépendants avec ses entreprises clientes à travers la France, la Belgique et le Luxembourg.</p><p>Le monde de l'immobilier n'échappe pas à ses talents. Il est le pionnier du modèle des réseaux de mandataires indépendants et développe le sourcing des structures aujourd'hui leaders sur le marché français — telles que IAD ou SAFTI — qui représentent à eux seuls 27% du marché de l'immobilier français.</p><p>Associé avec Wilfrid & Erwan dans e2w, il pilote et préside la filiale SUNCOM Facilities au sein de laquelle il fait vivre sa passion récente pour l'I.A. et l'automatisation au service de la prospection, de la vente et de la relation client. Le virage immobilier !</p>",
    wilfrid_role: "Fondateur & Associé — Président SUNCOM Estate",
    wilfrid_b1: "Commissaire de justice pendant 18 ans — France & Canada",
    wilfrid_b2: "Agent Immobilier pendant 15 ans — collabore avec une vingtaine d'agences en France",
    wilfrid_b3: "Formateur en continu des avocats inscrits au barreau du Québec pendant 3 ans",
    wilfrid_history: "Un peu d'histoire",
    wilfrid_bio: "<p>Né en 1965, après avoir usé ses fonds de culottes sur les bancs de la Faculté de droit de Rouen, il a exercé la profession de Commissaire de Justice pendant près de 20 ans, en France et en DOM-TOM.</p><p>Plus tard, le goût de l'immobilier lui est apparu lors de sa première association dans une agence montpelliéraine. Il collabore désormais avec une vingtaine d'agences en France.</p><p>Le projet e2w s'inscrit très précisément dans sa volonté d'aller plus loin dans l'innovation au travers d'un projet ambitieux à dimension internationale. Associé à Erwan & William dans la holding, il pilote et préside les activités immobilières de la filiale SUNCOM Estate.</p><p class=\"bio-quote\">« L'audace a du génie, du pouvoir, de la magie » — Goethe</p>",
    legal_title: "Mentions légales",
    legal_editor: "Éditeur",
    legal_host: "Hébergement",
    legal_ip: "Propriété intellectuelle",
    legal_ip_text: "L'ensemble des contenus présents sur ce site (textes, visuels, architecture) sont la propriété exclusive de e2w Holding et de ses filiales SUNCOM. Toute reproduction, même partielle, est interdite sans autorisation préalable écrite.",
    legal_data: "Données personnelles",
    legal_data_text: "Ce site ne collecte aucune donnée personnelle sans consentement explicite. Conformément au RGPD, vous disposez d'un droit d'accès, de rectification et de suppression de vos données. Contact : contact-e2w@pm.me",
    legal_cookies: "Cookies",
    legal_cookies_text: "Ce site utilise uniquement des cookies fonctionnels (préférence de thème). Aucun cookie publicitaire ou de traçage tiers n'est utilisé.",
    back_home: "← Accueil",
    buyest_cta: "Consulter les annonces",
    // suncom_landing_estate.html
    estate_back: "Accueil",
    estate_label: "SUNCOM Estate — Agents & Actionnaires",
    estate_h1: "Arrête d'enrichir<br><em>les autres.</em><br><span class=\"line-amber\">Deviens propriétaire</span><br>de la valeur que tu apportes.",
    estate_intro1: "<strong style=\"color:#ffffff;\">SUNCOM Estate</strong> n'est pas un réseau immobilier de plus.<br><br>C'est le seul modèle où les mandataires indépendants démultiplient les sources de rémunérations, entrent au capital, perçoivent des commissions, partagent les bénéfices, sans empiéter sur leur liberté.<br><br>Le reste, c'est juste un porteur de carte, des supports, des outils et des formations auxquels tout le monde a accès ; Abusé !",
    estate_quote1: "100% de la valeur ajoutée de l'agence ou du réseau <strong style=\"font-size:1.35em;\">c'est toi</strong> 🫵 !",
    estate_q2_title: "Tu vends, tu vis ; tu ne vends pas, tu meurs !",
    estate_q2_body: "Pas de ça avec <strong style=\"color:#ffffff;\">SUNCOM Estate</strong>, toujours des services rémunérés à proposer même en cas de baisse d'activité. Tu es la seule personne qui compte !",
    estate_stat1: "d'expérience",
    estate_stat2: "Actionnariat réel dès J1",
    estate_stat3: "Agents Commerciaux",
    estate_hero_cta: "Je veux rejoindre",
    estate_args_label: "Ce qui change tout",
    estate_a1_title: "Co-actionnaire",
    estate_a1_desc: "Tu entres au capital de SUNCOM Estate via BSA. Tes ventes valorisent une entreprise que tu possèdes — pas celle d'un fond d'investissement. Aucun risque pour toi ; tout bénéfice !",
    estate_a2_title: "Commissions Multiples",
    estate_a2_desc: "75% pour tout le monde, point final ! Par contre tu touches sur les prêts, les diags, les travaux, les piscines, les déménagements… Et en fin d'année, tous à New York pour la remise des dividendes !",
    estate_a3_title: "Sécurité juridique",
    estate_a3_desc: "Partenariat exclusif FIDAL en France et à l'international. Défense des intérêts de la société et de ses agents associés & actionnaires. N°1 des cabinets d'avocats.",
    estate_a4_title: "Outils, Tech et IA",
    estate_a4_desc: "Tous les canaux de diffusion, la prospection prédictive, les agents virtuels, chat bot, CRM multilingue, SaaS, API multisupports…",
    estate_a5_title: "Réseau fondateurs experts",
    estate_a5_desc: "Erwan Milbéo (35 ans d'immobilier international), Wilfrid Meyer (commissaire de justice, 60 agences), William Legendre (fondateur AgentCo, lanceur de IAD & SAFTI).",
    estate_a6_title: "Dimension internationale",
    estate_a6_desc: "Scaler rapidement, ensemble et à travers le monde. Objectif cotation en bourse. R&D active au sein de SUNCOM Lab à New York : vous y serez invité prochainement, aux frais de SUNCOM !",
    estate_form_label: "Candidature Mandataire & Associé",
    estate_form_title: "Rejoindre <span>SUNCOM</span><br>Estate",
    estate_form_sub: "10 questions · Profil validé sous 48h · Entretien avec les fondateurs",
    estate_form_timer: "2 minutes chrono",
    estate_bloc1: "01 — Identité",
    estate_bloc2: "02 — Situation actuelle",
    estate_bloc3: "03 — Motivation",
    estate_bloc4: "04 — Disponibilité",
    estate_submit: "Envoyer ma candidature",
    estate_form_legal: "Vos données sont traitées confidentiellement par e2w Holding / SUNCOM Estate.<br>Aucune diffusion à des tiers. Réponse garantie sous 48h.",
    estate_success_title: "Candidature reçue",
    estate_success_sub: "Merci. Votre profil est en cours d'analyse.<br>William Legendre vous contactera sous 48h.",
    estate_footer: "e2w Holding — © 2026 — Confidentiel",

  },

  en: {
    nav_cta: "Join",
    hero_eyebrow: "Real estate agents & Co-shareholders",
    hero_sub: "The future of real estate is written here",
    hero_scroll: "Discover",
    b1_tag: "Agents & Shareholders",
    b1_desc: "As an independent real estate agent, you become a partner & shareholder! You earn your commissions, share the profits; you have real capital and transferable assets at any time.<br><span style=\"color:#ffffff;\">Build yourself a future!</span>",
    b1_link: "Become a founding agent",
    b2_tag: "100% Real Estate Services",
    b2_desc: "Your clients need financing, a survey, a pool, an extension, a landscaper? Join our 52K agents and get your «<span style=\"font-size:0.85em;\">PASS FACILITIES</span>» with our 30K partner companies.<br><span style=\"color:#ffffff;\">More commissions, more profits!</span>",
    b2_link: "Learn more",
    b3_tag: "The Club",
    b3_desc: "Connect and share with your peers and partners within our private club. Discover the latest tools and winning strategies. Manage all your business on a single App.<br><span style=\"color:#ffffff;\">An international community!</span>",
    b3_link: "Join the network",
    b4_desc: "Join our international Think Tank in New York for research & development. Tech, A.I., SaaS, video, communication, social networks, intelligence, benchmarks… OPEN!<br><span style=\"color:#ffffff;\">Partner before 31.08.26 <span style=\"color:#F0A500;\">⌱</span> 1 round trip to New York from your capital!</span>",
    b4_link: "Discover the Lab",
    footer_rights: "All rights reserved",
    about_eyebrow: "⌱ SUNCOM Group",
    about_sub: "The legal and financial structure behind the SUNCOM ecosystem.",
    e2w_label: "Registered office",
    section_team: "Founders & Partners",
    bio_read: "Read biography",
    bio_hide: "Hide biography",
    erwan_role: "Founder & Partner — President e2w · SUNCOM Associates",
    erwan_b1: "Serial entrepreneur internationally since 1991 — Real Estate & New Technologies",
    erwan_b2: "Founder and CEO of companies in France, Italy, Spain, UK, Bahrain...",
    erwan_b3: "Up to 300 employees worldwide — partnerships with Canal+ / Air France / Iberia",
    erwan_history: "A bit of history",
    erwan_bio: "<p>Born in 1966, after a youth as a competitive athlete, he spent 3 years studying foreign languages and civilizations before realizing this path wasn't for him. He needed action!</p><p>For 35 years, he has been creating, managing and holding shares in international companies in real estate and new technologies. In partnership with Canal Plus, Air France and Iberia groups, he was the only executive to have a counter in his company's name at Paris airports and to own his own airliner to accompany clients to luxury real estate developments worldwide.</p><p>With the advent of the Internet, his company MKT Lines became one of the leaders in reverse engineering and Search Engine Optimization. He now actively leads the SUNCOM project alongside his long-time partners William & Wilfrid.</p>",
    william_role: "Founder & Partner — President SUNCOM Facilities",
    william_b1: "Founder and manager since 1999 of the 1st network of Commercial Agents and Freelancers",
    william_b2: "Leader for 25 years — 57,000 Commercial Agents managed — 30,000 client companies",
    william_b3: "€55 billion in annual revenue generated by his teams",
    william_history: "A bit of history",
    william_bio: "<p>Sales is his engine! Born in 1975, graduated from ESC Reims and EAP Paris-Champernet, he founded the AgentCo platform over 25 years ago and became the N°1 in recruiting and connecting independent commercial agents with client companies across France, Belgium and Luxembourg.</p><p>Real estate didn't escape his talent. He is the pioneer of the independent agent network model and developed the sourcing of structures now leading the French market — such as IAD and SAFTI — which alone represent 27% of the French real estate market.</p><p>As a partner with Wilfrid & Erwan at e2w, he leads SUNCOM Facilities where he combines his recent passion for A.I. and automation in sales and client relations.</p>",
    wilfrid_role: "Founder & Partner — President SUNCOM Estate",
    wilfrid_b1: "Judicial officer for 18 years — France & Canada",
    wilfrid_b2: "Real estate agent for 15 years — works with around twenty agencies in France",
    wilfrid_b3: "Continuing trainer for lawyers at the Quebec Bar for 3 years",
    wilfrid_history: "A bit of history",
    wilfrid_bio: "<p>Born in 1965, he practiced as a Judicial Officer for nearly 20 years in France and the French overseas territories after studying law in Rouen.</p><p>His passion for real estate emerged about twenty years ago during his first association with an agency in Montpellier. He now collaborates with around twenty agencies in France.</p><p>The e2w project perfectly aligns with his desire to push innovation further through an ambitious international project. As a partner with Erwan & William in the holding, he leads SUNCOM Estate's real estate activities.</p><p class=\"bio-quote\">« Boldness has genius, power and magic in it » — Goethe</p>",
    legal_title: "Legal notices",
    legal_editor: "Publisher",
    legal_host: "Hosting",
    legal_ip: "Intellectual property",
    legal_ip_text: "All content on this site (texts, visuals, architecture) is the exclusive property of e2w Holding and its SUNCOM subsidiaries. Any reproduction, even partial, is prohibited without prior written authorization.",
    legal_data: "Personal data",
    legal_data_text: "This site does not collect any personal data without explicit consent. In accordance with GDPR, you have the right to access, rectify and delete your data. Contact: contact-e2w@pm.me",
    legal_cookies: "Cookies",
    legal_cookies_text: "This site uses only functional cookies (theme preference). No advertising or third-party tracking cookies are used.",
    back_home: "← Home",
    buyest_cta: "Browse listings",
    // suncom_landing_estate.html
    estate_back: "Back",
    estate_label: "SUNCOM Estate — Agents & Shareholders",
    estate_h1: "Stop enriching<br><em>others.</em><br><span class=\"line-amber\">Own the value</span><br>you bring to the table.",
    estate_intro1: "<strong style=\"color:#ffffff;\">SUNCOM Estate</strong> is not just another real estate network.<br><br>It's the only model where independent agents multiply their income streams, enter the capital, earn commissions and share profits — without sacrificing their freedom.<br><br>Everything else just gives you a card, some tools and training anyone can access. Really?",
    estate_quote1: "100% of the agency's added value <strong style=\"font-size:1.35em;\">is you</strong> 🫵!",
    estate_q2_title: "You sell, you live; you don't sell, you're done!",
    estate_q2_body: "Not with <strong style=\"color:#ffffff;\">SUNCOM Estate</strong> — always paid services to offer, even during slow periods. You're the only one who matters here!",
    estate_stat1: "of experience",
    estate_stat2: "Real equity from day 1",
    estate_stat3: "Commercial Agents",
    estate_hero_cta: "I want to join",
    estate_args_label: "What changes everything",
    estate_a1_title: "Co-shareholder",
    estate_a1_desc: "You enter SUNCOM Estate's capital via BSA. Your sales grow a company you own — not a fund's. Zero risk for you; all upside.",
    estate_a2_title: "Multiple Commissions",
    estate_a2_desc: "75% for everyone, full stop. Plus you earn on loans, surveys, works, pools, moves… And at year end, everyone flies to New York for the dividend ceremony!",
    estate_a3_title: "Legal security",
    estate_a3_desc: "Exclusive FIDAL partnership in France and internationally. Protecting the interests of the company and its agent-shareholders. France's #1 law firm.",
    estate_a4_title: "Tools, Tech & AI",
    estate_a4_desc: "All broadcast channels, predictive prospecting, virtual agents, chatbot, multilingual CRM, SaaS, multi-support APIs…",
    estate_a5_title: "Expert founder network",
    estate_a5_desc: "Erwan Milbéo (35 years international real estate), Wilfrid Meyer (judicial officer, 60 agencies), William Legendre (AgentCo founder, launched IAD & SAFTI).",
    estate_a6_title: "International reach",
    estate_a6_desc: "Scale fast, together, worldwide. Target: stock market listing. Active R&D at SUNCOM Lab in New York — you'll be invited soon, on SUNCOM's dime!",
    estate_form_label: "Agent & Partner Application",
    estate_form_title: "Join <span>SUNCOM</span><br>Estate",
    estate_form_sub: "10 questions · Profile validated within 48h · Interview with the founders",
    estate_form_timer: "2 minutes",
    estate_bloc1: "01 — Identity",
    estate_bloc2: "02 — Current situation",
    estate_bloc3: "03 — Motivation",
    estate_bloc4: "04 — Availability",
    estate_submit: "Submit my application",
    estate_form_legal: "Your data is handled confidentially by e2w Holding / SUNCOM Estate.<br>No third-party sharing. Reply guaranteed within 48h.",
    estate_success_title: "Application received",
    estate_success_sub: "Thank you. Your profile is being reviewed.<br>William Legendre will contact you within 48h.",
    estate_footer: "e2w Holding — © 2026 — Confidential",

  },

  de: {
    nav_cta: "Beitreten",
    hero_eyebrow: "Immobilienmakler & Mitaktionäre",
    hero_sub: "Die Zukunft der Immobilien wird hier geschrieben",
    hero_scroll: "Entdecken",
    b1_tag: "Agenten & Aktionäre",
    b1_desc: "Als unabhängiger Immobilienmakler wirst du Partner & Aktionär! Du erhältst deine Provisionen, teilst die Gewinne; du hast echtes Kapital und jederzeit übertragbares Vermögen.<br><span style=\"color:#ffffff;\">Bau dir eine Zukunft auf!</span>",
    b1_link: "Gründungsagent werden",
    b2_tag: "100% Immobiliendienstleistungen",
    b2_desc: "Deine Kunden brauchen Finanzierung, Gutachten, Pool, Anbau, Landschaftsgärtner? Schließ dich unseren 52K Agenten an und erhalte deinen «<span style=\"font-size:0.85em;\">PASS FACILITIES</span>» mit unseren 30K Partnern.<br><span style=\"color:#ffffff;\">Mehr Provisionen, mehr Gewinn!</span>",
    b2_link: "Mehr erfahren",
    b3_tag: "Der Club",
    b3_desc: "Tausch dich mit Kollegen und Partnern in unserem privaten Club aus. Entdecke neueste Tools und Erfolgsstrategien. Verwalte all deine Geschäfte in einer App.<br><span style=\"color:#ffffff;\">Eine internationale Community!</span>",
    b3_link: "Dem Netzwerk beitreten",
    b4_desc: "Nimm an F&E teil und tritt unserem internationalen Think Tank in New York bei. Tech, K.I., SaaS, Video, Kommunikation, Social Networks, Benchmarks… OPEN!<br><span style=\"color:#ffffff;\">Partner vor dem 31.08.26 <span style=\"color:#F0A500;\">⌱</span> 1 Hin- und Rückflug nach New York!</span>",
    b4_link: "Das Lab entdecken",
    footer_rights: "Alle Rechte vorbehalten",
    about_eyebrow: "⌱ SUNCOM Gruppe",
    about_sub: "Die rechtliche und finanzielle Struktur hinter dem SUNCOM-Ökosystem.",
    e2w_label: "Hauptsitz",
    section_team: "Gründer & Partner",
    bio_read: "Biografie lesen",
    bio_hide: "Biografie ausblenden",
    erwan_role: "Gründer & Partner — Präsident e2w · SUNCOM Associates",
    erwan_b1: "Serial-Unternehmer international seit 1991 — Immobilien & Neue Technologien",
    erwan_b2: "Gründer und Geschäftsführer von Gesellschaften in Frankreich, Italien, Spanien, GB, Bahrain...",
    erwan_b3: "Bis zu 300 Mitarbeiter weltweit — Partnerschaften mit Canal+ / Air France / Iberia",
    erwan_history: "Ein bisschen Geschichte",
    erwan_bio: "<p>Geboren 1966, erhielt er nach einer Jugend als Leistungssportler 3 Jahre Universitätsausbildung in Fremdsprachen, bevor er merkte, dass dieser Weg nicht zu ihm passte. Er brauchte Action!</p><p>Seit 35 Jahren gründet, leitet und beteiligt er sich an internationalen Unternehmen in den Bereichen Immobilien und neue Technologien. Er leitete Partnerschaften mit Canal Plus, Air France und Iberia und war der einzige Geschäftsführer mit einem Schalter an Pariser Flughäfen sowie einem eigenen Linienflugzeug für seine Klientel.</p><p>Er widmet sich nun aktiv dem SUNCOM-Projekt gemeinsam mit seinen langjährigen Partnern William & Wilfrid.</p>",
    william_role: "Gründer & Partner — Präsident SUNCOM Facilities",
    william_b1: "Gründer und Leiter seit 1999 des 1. Netzwerks für Handelsvertreter und Freelancer",
    william_b2: "Marktführer seit 25 Jahren — 57.000 Handelsvertreter — 30.000 Kundenunternehmen",
    william_b3: "55 Milliarden Euro Jahresumsatz durch seine Teams",
    william_history: "Ein bisschen Geschichte",
    william_bio: "<p>Verkauf ist sein Motor! Geboren 1975, Absolvent der ESC Reims und EAP Paris-Champernet, gründete er die Plattform AgentCo vor über 25 Jahren und wurde zur N°1 im Recruiting von Handelsvertretern in Frankreich, Belgien und Luxemburg.</p><p>Er ist Pionier des Modells unabhängiger Maklernetzwerke und entwickelte das Sourcing von Strukturen wie IAD und SAFTI, die heute 27% des französischen Immobilienmarktes ausmachen.</p><p>Als Partner bei e2w leitet er SUNCOM Facilities und verbindet seine Leidenschaft für K.I. und Automatisierung im Vertrieb.</p>",
    wilfrid_role: "Gründer & Partner — Präsident SUNCOM Estate",
    wilfrid_b1: "Gerichtsvollzieher für 18 Jahre — Frankreich & Kanada",
    wilfrid_b2: "Immobilienmakler für 15 Jahre — arbeitet mit rund zwanzig Agenturen in Frankreich",
    wilfrid_b3: "Fortbildner für Anwälte der Québecer Anwaltskammer für 3 Jahre",
    wilfrid_history: "Ein bisschen Geschichte",
    wilfrid_bio: "<p>Geboren 1965, übte er nach seinem Jurastudium in Rouen fast 20 Jahre lang den Beruf des Gerichtsvollziehers aus. Später entdeckte er seine Leidenschaft für Immobilien und arbeitet heute mit rund zwanzig Agenturen in Frankreich zusammen.</p><p>Das e2w-Projekt entspricht seinem Wunsch, durch ein ehrgeiziges internationales Projekt weitere Innovationen voranzutreiben. Als Partner mit Erwan & William leitet er SUNCOM Estate.</p><p class=\"bio-quote\">« Kühnheit hat Genie, Kraft und Magie » — Goethe</p>",
    legal_title: "Impressum & Rechtliches",
    legal_editor: "Herausgeber",
    legal_host: "Hosting",
    legal_ip: "Geistiges Eigentum",
    legal_ip_text: "Alle Inhalte dieser Website (Texte, Grafiken, Architektur) sind ausschließliches Eigentum von e2w Holding und ihren SUNCOM-Tochtergesellschaften. Jegliche Reproduktion, auch auszugsweise, ist ohne vorherige schriftliche Genehmigung untersagt.",
    legal_data: "Personenbezogene Daten",
    legal_data_text: "Diese Website erhebt keine personenbezogenen Daten ohne ausdrückliche Einwilligung. Gemäß DSGVO haben Sie das Recht auf Zugang, Berichtigung und Löschung Ihrer Daten. Kontakt: contact-e2w@pm.me",
    legal_cookies: "Cookies",
    legal_cookies_text: "Diese Website verwendet nur funktionale Cookies (Themenpräferenz). Es werden keine Werbe- oder Tracking-Cookies von Drittanbietern verwendet.",
    back_home: "← Startseite",
    buyest_cta: "Angebote ansehen",
    // suncom_landing_estate.html
    estate_back: "Zurück",
    estate_label: "SUNCOM Estate — Agents & Aktionäre",
    estate_h1: "Hör auf, andere<br><em>zu bereichern.</em><br><span class=\"line-amber\">Werde Eigentümer</span><br>des Werts, den du schaffst.",
    estate_intro1: "<strong style=\"color:#ffffff;\">SUNCOM Estate</strong> ist kein gewöhnliches Immobiliennetzwerk.<br><br>Es ist das einzige Modell, bei dem unabhängige Makler ihre Einkommensquellen vervielfachen, ins Kapital eintreten, Provisionen erhalten und Gewinne teilen — ohne ihre Freiheit zu opfern.<br><br>Der Rest gibt dir nur eine Visitenkarte, Tools und Schulungen, die jeder hat. Ernsthaft?",
    estate_quote1: "100% des Mehrwerts der Agentur <strong style=\"font-size:1.35em;\">bist du</strong> 🫵!",
    estate_q2_title: "Du verkaufst, du lebst; du verkaufst nicht, du stirbst!",
    estate_q2_body: "Nicht bei <strong style=\"color:#ffffff;\">SUNCOM Estate</strong> — immer bezahlte Dienstleistungen, auch in schwachen Phasen. Du bist die einzige Person, die zählt!",
    estate_stat1: "Erfahrung",
    estate_stat2: "Echte Beteiligung ab Tag 1",
    estate_stat3: "Handelsvertreter",
    estate_hero_cta: "Ich möchte beitreten",
    estate_args_label: "Was alles verändert",
    estate_a1_title: "Mitaktionär",
    estate_a1_desc: "Du trittst via BSA ins Kapital von SUNCOM Estate ein. Deine Verkäufe steigern den Wert eines Unternehmens, das dir gehört — kein Investmentfonds. Null Risiko, voller Gewinn.",
    estate_a2_title: "Mehrfache Provisionen",
    estate_a2_desc: "75% für alle, Punkt. Plus verdienst du an Krediten, Gutachten, Renovierungen, Pools, Umzügen… Und am Jahresende fliegen alle nach New York zur Dividendenübergabe!",
    estate_a3_title: "Rechtssicherheit",
    estate_a3_desc: "Exklusivpartnerschaft mit FIDAL in Frankreich und international. Schutz der Interessen des Unternehmens und seiner Agenten-Aktionäre. Frankreichs führende Anwaltskanzlei.",
    estate_a4_title: "Tools, Tech & KI",
    estate_a4_desc: "Alle Werbekanäle, prädiktive Akquise, virtuelle Agenten, Chatbot, mehrsprachiges CRM, SaaS, Multi-API…",
    estate_a5_title: "Expertengründernetzwerk",
    estate_a5_desc: "Erwan Milbéo (35 Jahre internationales Immobiliengeschäft), Wilfrid Meyer (Gerichtsvollzieher, 60 Agenturen), William Legendre (Gründer AgentCo, Initiator von IAD & SAFTI).",
    estate_a6_title: "Internationale Dimension",
    estate_a6_desc: "Gemeinsam und weltweit schnell skalieren. Ziel: Börsennotierung. Aktive F&E im SUNCOM Lab in New York — du wirst bald auf SUNCOM's Kosten eingeladen!",
    estate_form_label: "Bewerbung Makler & Partner",
    estate_form_title: "Treten Sie <span>SUNCOM</span><br>Estate bei",
    estate_form_sub: "10 Fragen · Profil innerhalb von 48h validiert · Interview mit den Gründern",
    estate_form_timer: "2 Minuten",
    estate_bloc1: "01 — Identität",
    estate_bloc2: "02 — Aktuelle Situation",
    estate_bloc3: "03 — Motivation",
    estate_bloc4: "04 — Verfügbarkeit",
    estate_submit: "Bewerbung absenden",
    estate_form_legal: "Ihre Daten werden von e2w Holding / SUNCOM Estate vertraulich behandelt.<br>Keine Weitergabe an Dritte. Antwort garantiert innerhalb von 48h.",
    estate_success_title: "Bewerbung erhalten",
    estate_success_sub: "Danke. Ihr Profil wird geprüft.<br>William Legendre wird Sie innerhalb von 48h kontaktieren.",
    estate_footer: "e2w Holding — © 2026 — Vertraulich",

  },

  es: {
    nav_cta: "Unirse",
    hero_eyebrow: "Agentes inmobiliarios & Co-accionistas",
    hero_sub: "El futuro del inmobiliario se escribe aquí",
    hero_scroll: "Descubrir",
    b1_tag: "Agentes & Accionistas",
    b1_desc: "Como mandatario independiente en el sector inmobiliario, ¡te conviertes en socio & accionista! Cobras tus comisiones, compartes los beneficios; tienes un capital real y un patrimonio transmisible.<br><span style=\"color:#ffffff;\">¡Construye tu futuro!</span>",
    b1_link: "Convertirse en agente fundador",
    b2_tag: "100% Servicios Inmobiliarios",
    b2_desc: "¿Tus clientes necesitan financiación, diagnóstico, piscina, ampliación, paisajista? Únete a nuestros 52K agentes y obtén tu «<span style=\"font-size:0.85em;\">PASS FACILITIES</span>» con nuestras 30K empresas.<br><span style=\"color:#ffffff;\">¡Más comisiones, más beneficios!</span>",
    b2_link: "Más información",
    b3_tag: "El Club",
    b3_desc: "Intercambia y comparte con tus colegas y socios en nuestro club privado. Descubre las últimas herramientas y tácticas ganadoras. Consulta todos tus negocios en una sola App.<br><span style=\"color:#ffffff;\">¡Una comunidad internacional!</span>",
    b3_link: "Unirse a la red",
    b4_desc: "Participa en I+D uniéndote a nuestro Think Tank internacional en Nueva York. Tech, I.A., SaaS, vídeo, comunicación, redes sociales, benchmarks… ¡OPEN!<br><span style=\"color:#ffffff;\">Asociado antes del 31.08.26 <span style=\"color:#F0A500;\">⌱</span> ¡1 vuelta a Nueva York desde tu capital!</span>",
    b4_link: "Descubrir el Lab",
    footer_rights: "Todos los derechos reservados",
    about_eyebrow: "⌱ Grupo SUNCOM",
    about_sub: "La estructura jurídica y financiera detrás del ecosistema SUNCOM.",
    e2w_label: "Sede social",
    section_team: "Fundadores & Socios",
    bio_read: "Leer biografía",
    bio_hide: "Ocultar biografía",
    erwan_role: "Fundador & Socio — Presidente e2w · SUNCOM Associates",
    erwan_b1: "Emprendedor en serie a nivel internacional desde 1991 — Inmobiliario & Nuevas Tecnologías",
    erwan_b2: "Fundador y Director de Sociedades en Francia, Italia, España, GB, Bahrein...",
    erwan_b3: "Hasta 300 empleados en todo el mundo — asociaciones con Canal+ / Air France / Iberia",
    erwan_history: "Un poco de historia",
    erwan_bio: "<p>Nacido en 1966, tras una juventud deportiva de alto nivel, estudió 3 años de lenguas y civilizaciones extranjeras antes de comprender que necesitaba acción.</p><p>Durante 35 años ha creado, dirigido y participado como accionista en empresas internacionales en inmobiliario y nuevas tecnologías. En asociación con Canal Plus, Air France e Iberia, fue el único directivo con un mostrador propio en aeropuertos de París y propietario de su propio avión de línea para acompañar a clientes en promociones inmobiliarias de lujo.</p><p>Se dedica ahora activamente al proyecto SUNCOM junto a sus socios de larga data William & Wilfrid.</p>",
    william_role: "Fundador & Socio — Presidente SUNCOM Facilities",
    william_b1: "Fundador y gestor desde 1999 de la 1ª red de Agentes Comerciales y Freelances",
    william_b2: "Líder durante 25 años — 57.000 Agentes gestionados — 30.000 empresas clientes",
    william_b3: "55.000 millones de euros de facturación anual generada por sus equipos",
    william_history: "Un poco de historia",
    william_bio: "<p>¡El universo de la venta es su motor! Nacido en 1975, fundó la plataforma AgentCo hace más de 25 años y se convirtió en el N°1 del reclutamiento de agentes comerciales independientes en Francia, Bélgica y Luxemburgo.</p><p>Es pionero del modelo de redes de mandatarios independientes y desarrolló el sourcing de estructuras líderes como IAD y SAFTI, que representan el 27% del mercado inmobiliario francés.</p><p>Socio con Wilfrid & Erwan en e2w, dirige SUNCOM Facilities combinando su pasión por la I.A. y la automatización al servicio de las ventas.</p>",
    wilfrid_role: "Fundador & Socio — Presidente SUNCOM Estate",
    wilfrid_b1: "Comisario de justicia durante 18 años — Francia & Canadá",
    wilfrid_b2: "Agente Inmobiliario durante 15 años — colabora con una veintena de agencias en Francia",
    wilfrid_b3: "Formador continuo de abogados del Colegio de Abogados de Quebec durante 3 años",
    wilfrid_history: "Un poco de historia",
    wilfrid_bio: "<p>Nacido en 1965, ejerció como Comisario de Justicia durante casi 20 años en Francia y territorios de ultramar tras estudiar derecho en Rouen. Más tarde descubrió su pasión por el inmobiliario y colabora hoy con una veintena de agencias en Francia.</p><p>El proyecto e2w responde a su voluntad de innovar a través de un proyecto internacional ambicioso. Socio de Erwan & William, dirige las actividades inmobiliarias de SUNCOM Estate.</p><p class=\"bio-quote\">« La audacia tiene genio, poder y magia » — Goethe</p>",
    legal_title: "Avisos legales",
    legal_editor: "Editor",
    legal_host: "Alojamiento",
    legal_ip: "Propiedad intelectual",
    legal_ip_text: "Todos los contenidos de este sitio (textos, visuales, arquitectura) son propiedad exclusiva de e2w Holding y sus filiales SUNCOM. Cualquier reproducción, incluso parcial, está prohibida sin autorización previa por escrito.",
    legal_data: "Datos personales",
    legal_data_text: "Este sitio no recoge datos personales sin consentimiento explícito. De acuerdo con el RGPD, dispone de derechos de acceso, rectificación y supresión de sus datos. Contacto: contact-e2w@pm.me",
    legal_cookies: "Cookies",
    legal_cookies_text: "Este sitio utiliza únicamente cookies funcionales (preferencia de tema). No se utilizan cookies publicitarias ni de rastreo de terceros.",
    back_home: "← Inicio",
    buyest_cta: "Ver anuncios",
    // suncom_landing_estate.html
    estate_back: "Volver",
    estate_label: "SUNCOM Estate — Agentes & Accionistas",
    estate_h1: "Deja de enriquecer<br><em>a los demás.</em><br><span class=\"line-amber\">Sé propietario</span><br>del valor que aportas.",
    estate_intro1: "<strong style=\"color:#ffffff;\">SUNCOM Estate</strong> no es una red inmobiliaria más.<br><br>Es el único modelo donde los mandatarios independientes multiplican sus fuentes de ingresos, entran al capital, perciben comisiones y comparten beneficios — sin sacrificar su libertad.<br><br>Lo demás solo te da una tarjeta, herramientas y formaciones a las que todo el mundo tiene acceso. ¿En serio?",
    estate_quote1: "El 100% del valor añadido de la agencia <strong style=\"font-size:1.35em;\">eres tú</strong> 🫵!",
    estate_q2_title: "¡Vendes, vives; no vendes, mueres!",
    estate_q2_body: "Con <strong style=\"color:#ffffff;\">SUNCOM Estate</strong> no es así — siempre hay servicios remunerados que ofrecer, incluso en épocas difíciles. ¡Tú eres la única persona que importa!",
    estate_stat1: "de experiencia",
    estate_stat2: "Capital real desde el día 1",
    estate_stat3: "Agentes Comerciales",
    estate_hero_cta: "Quiero unirme",
    estate_args_label: "Lo que lo cambia todo",
    estate_a1_title: "Co-accionista",
    estate_a1_desc: "Entras al capital de SUNCOM Estate vía BSA. Tus ventas valorizan una empresa que tú posees — no un fondo. Cero riesgo para ti; todo beneficio.",
    estate_a2_title: "Comisiones Múltiples",
    estate_a2_desc: "75% para todos, punto final. Además cobras por préstamos, diagnósticos, obras, piscinas, mudanzas… ¡Y a final de año, todos a Nueva York para la entrega de dividendos!",
    estate_a3_title: "Seguridad jurídica",
    estate_a3_desc: "Asociación exclusiva con FIDAL en Francia e internacionalmente. Defensa de los intereses de la empresa y sus agentes-accionistas. El despacho #1 de abogados.",
    estate_a4_title: "Herramientas, Tech e IA",
    estate_a4_desc: "Todos los canales de difusión, prospección predictiva, agentes virtuales, chatbot, CRM multilingüe, SaaS, APIs multisupporte…",
    estate_a5_title: "Red de fundadores expertos",
    estate_a5_desc: "Erwan Milbéo (35 años en inmobiliario internacional), Wilfrid Meyer (comisario de justicia, 60 agencias), William Legendre (fundador AgentCo, lanzador de IAD & SAFTI).",
    estate_a6_title: "Dimensión internacional",
    estate_a6_desc: "Escalar rápido, juntos y en todo el mundo. Objetivo: cotización en bolsa. I+D activa en SUNCOM Lab en Nueva York: ¡serás invitado pronto, a cargo de SUNCOM!",
    estate_form_label: "Candidatura Mandatario & Socio",
    estate_form_title: "Únete a <span>SUNCOM</span><br>Estate",
    estate_form_sub: "10 preguntas · Perfil validado en 48h · Entrevista con los fundadores",
    estate_form_timer: "2 minutos",
    estate_bloc1: "01 — Identidad",
    estate_bloc2: "02 — Situación actual",
    estate_bloc3: "03 — Motivación",
    estate_bloc4: "04 — Disponibilidad",
    estate_submit: "Enviar mi candidatura",
    estate_form_legal: "Sus datos son tratados confidencialmente por e2w Holding / SUNCOM Estate.<br>Sin difusión a terceros. Respuesta garantizada en 48h.",
    estate_success_title: "Candidatura recibida",
    estate_success_sub: "Gracias. Su perfil está siendo analizado.<br>William Legendre le contactará en 48h.",
    estate_footer: "e2w Holding — © 2026 — Confidencial",

  },

  pt: {
    nav_cta: "Aderir",
    hero_eyebrow: "Agentes imobiliários & Co-acionistas",
    hero_sub: "O futuro do imobiliário escreve-se aqui",
    hero_scroll: "Descobrir",
    b1_tag: "Agentes & Acionistas",
    b1_desc: "Como mandatário independente no setor imobiliário, tornas-te sócio & acionista! Recebes as tuas comissões, partilhas os lucros; tens capital real e um patrimônio transmissível a qualquer momento.<br><span style=\"color:#ffffff;\">Constrói o teu futuro!</span>",
    b1_link: "Tornar-se agente fundador",
    b2_tag: "100% Serviços Imobiliários",
    b2_desc: "Os teus clientes precisam de financiamento, diagnóstico, piscina, extensão, paisagista? Junta-te aos nossos 52K agentes e obtém o teu «<span style=\"font-size:0.85em;\">PASS FACILITIES</span>» com as nossas 30K empresas.<br><span style=\"color:#ffffff;\">Mais comissões, mais lucros!</span>",
    b2_link: "Saber mais",
    b3_tag: "O Clube",
    b3_desc: "Troca e partilha com os teus colegas e sócios no nosso clube privado. Descobre as últimas ferramentas e táticas vencedoras. Consulta todos os teus negócios numa só App.<br><span style=\"color:#ffffff;\">Uma comunidade internacional!</span>",
    b3_link: "Aderir à rede",
    b4_desc: "Participa em I&D juntando-te ao nosso Think Tank internacional em Nova Iorque. Tech, I.A., SaaS, vídeo, comunicação, redes sociais, benchmarks… OPEN!<br><span style=\"color:#ffffff;\">Associado antes de 31.08.26 <span style=\"color:#F0A500;\">⌱</span> 1 ida e volta para Nova Iorque oferecida!</span>",
    b4_link: "Descobrir o Lab",
    footer_rights: "Todos os direitos reservados",
    about_eyebrow: "⌱ Grupo SUNCOM",
    about_sub: "A estrutura jurídica e financeira por trás do ecossistema SUNCOM.",
    e2w_label: "Sede social",
    section_team: "Fundadores & Sócios",
    bio_read: "Ler biografia",
    bio_hide: "Ocultar biografia",
    erwan_role: "Fundador & Sócio — Presidente e2w · SUNCOM Associates",
    erwan_b1: "Empreendedor em série a nível internacional desde 1991 — Imobiliário & Novas Tecnologias",
    erwan_b2: "Fundador e Diretor de Sociedades em França, Itália, Espanha, GB, Bahrain...",
    erwan_b3: "Até 300 colaboradores no mundo — parcerias com Canal+ / Air France / Iberia",
    erwan_history: "Um pouco de história",
    erwan_bio: "<p>Nascido em 1966, após uma juventude de desportista de alta competição, estudou 3 anos de línguas e civilizações estrangeiras antes de perceber que precisava de ação.</p><p>Há 35 anos cria, dirige e detém participações em empresas internacionais nos setores imobiliário e de novas tecnologias. Em parceria com a Canal Plus, Air France e Iberia, foi o único dirigente com um balcão próprio nos aeroportos de Paris e proprietário do seu próprio avião de linha.</p><p>Dedica-se agora ativamente ao projeto SUNCOM com os seus sócios de longa data William & Wilfrid.</p>",
    william_role: "Fundador & Sócio — Presidente SUNCOM Facilities",
    william_b1: "Fundador e gestor desde 1999 da 1ª rede de Agentes Comerciais e Freelancers",
    william_b2: "Líder há 25 anos — 57.000 Agentes geridos — 30.000 empresas clientes",
    william_b3: "55 mil milhões de euros de volume de negócios gerado anualmente pelas suas equipas",
    william_history: "Um pouco de história",
    william_bio: "<p>O universo das vendas é o seu motor! Nascido em 1975, fundou a plataforma AgentCo há mais de 25 anos e tornou-se N°1 no recrutamento de agentes comerciais independentes em França, Bélgica e Luxemburgo.</p><p>É pioneiro do modelo de redes de mandatários independentes e desenvolveu o sourcing de estruturas como a IAD e a SAFTI, que representam 27% do mercado imobiliário francês.</p><p>Sócio com Wilfrid & Erwan na e2w, lidera a SUNCOM Facilities combinando a sua paixão pela I.A. e automação ao serviço das vendas.</p>",
    wilfrid_role: "Fundador & Sócio — Presidente SUNCOM Estate",
    wilfrid_b1: "Comissário de justiça durante 18 anos — França & Canadá",
    wilfrid_b2: "Agente Imobiliário durante 15 anos — colabora com cerca de vinte agências em França",
    wilfrid_b3: "Formador contínuo de advogados inscritos na Ordem dos Advogados do Québec durante 3 anos",
    wilfrid_history: "Um pouco de história",
    wilfrid_bio: "<p>Nascido em 1965, exerceu a profissão de Comissário de Justiça durante quase 20 anos em França e territórios ultramarinos. Mais tarde descobriu a sua paixão pelo imobiliário e colabora hoje com cerca de vinte agências em França.</p><p>O projeto e2w insere-se na sua vontade de ir mais longe na inovação através de um projeto internacional ambicioso. Sócio de Erwan & William, lidera as atividades imobiliárias da SUNCOM Estate.</p><p class=\"bio-quote\">« A audácia tem génio, poder e magia » — Goethe</p>",
    legal_title: "Avisos legais",
    legal_editor: "Editor",
    legal_host: "Alojamento",
    legal_ip: "Propriedade intelectual",
    legal_ip_text: "Todo o conteúdo deste site (textos, visuais, arquitetura) é propriedade exclusiva da e2w Holding e das suas filiais SUNCOM. Qualquer reprodução, mesmo parcial, é proibida sem autorização prévia por escrito.",
    legal_data: "Dados pessoais",
    legal_data_text: "Este site não recolhe dados pessoais sem consentimento explícito. De acordo com o RGPD, tem direito de acesso, retificação e eliminação dos seus dados. Contacto: contact-e2w@pm.me",
    legal_cookies: "Cookies",
    legal_cookies_text: "Este site utiliza apenas cookies funcionais (preferência de tema). Não são utilizados cookies publicitários ou de rastreio de terceiros.",
    back_home: "← Início",
    buyest_cta: "Ver anúncios",
    // suncom_landing_estate.html
    estate_back: "Voltar",
    estate_label: "SUNCOM Estate — Agentes & Acionistas",
    estate_h1: "Para de enriquecer<br><em>os outros.</em><br><span class=\"line-amber\">Torna-te proprietário</span><br>do valor que trazes.",
    estate_intro1: "<strong style=\"color:#ffffff;\">SUNCOM Estate</strong> não é mais uma rede imobiliária.<br><br>É o único modelo onde os mandatários independentes multiplicam as suas fontes de rendimento, entram no capital, recebem comissões e partilham lucros — sem sacrificar a sua liberdade.<br><br>O resto dá-te apenas um cartão, ferramentas e formações a que toda a gente tem acesso. A sério?",
    estate_quote1: "100% do valor acrescentado da agência <strong style=\"font-size:1.35em;\">és tu</strong> 🫵!",
    estate_q2_title: "Vendes, vives; não vendes, morres!",
    estate_q2_body: "Não com a <strong style=\"color:#ffffff;\">SUNCOM Estate</strong> — sempre há serviços remunerados a oferecer, mesmo em períodos difíceis. Tu és a única pessoa que conta!",
    estate_stat1: "de experiência",
    estate_stat2: "Capital real desde o dia 1",
    estate_stat3: "Agentes Comerciais",
    estate_hero_cta: "Quero aderir",
    estate_args_label: "O que muda tudo",
    estate_a1_title: "Co-acionista",
    estate_a1_desc: "Entras no capital da SUNCOM Estate via BSA. As tuas vendas valorizam uma empresa que possuis — não um fundo. Zero risco; todo o benefício.",
    estate_a2_title: "Comissões Múltiplas",
    estate_a2_desc: "75% para todos, ponto final. Além disso recebes sobre empréstimos, diagnósticos, obras, piscinas, mudanças… E no final do ano, todos a Nova Iorque para a entrega de dividendos!",
    estate_a3_title: "Segurança jurídica",
    estate_a3_desc: "Parceria exclusiva com FIDAL em França e internacionalmente. Defesa dos interesses da empresa e dos seus agentes-acionistas. Escritório de advocacia n.º 1.",
    estate_a4_title: "Ferramentas, Tech e IA",
    estate_a4_desc: "Todos os canais de difusão, prospeção preditiva, agentes virtuais, chatbot, CRM multilingue, SaaS, APIs multi-suporte…",
    estate_a5_title: "Rede de fundadores especializados",
    estate_a5_desc: "Erwan Milbéo (35 anos em imobiliário internacional), Wilfrid Meyer (comissário de justiça, 60 agências), William Legendre (fundador AgentCo, lançador de IAD & SAFTI).",
    estate_a6_title: "Dimensão internacional",
    estate_a6_desc: "Crescer rapidamente, juntos e em todo o mundo. Objetivo: cotação em bolsa. I&D ativa no SUNCOM Lab em Nova Iorque — serás convidado em breve, a cargo da SUNCOM!",
    estate_form_label: "Candidatura Mandatário & Sócio",
    estate_form_title: "Aderir à <span>SUNCOM</span><br>Estate",
    estate_form_sub: "10 perguntas · Perfil validado em 48h · Entrevista com os fundadores",
    estate_form_timer: "2 minutos",
    estate_bloc1: "01 — Identidade",
    estate_bloc2: "02 — Situação atual",
    estate_bloc3: "03 — Motivação",
    estate_bloc4: "04 — Disponibilidade",
    estate_submit: "Enviar a minha candidatura",
    estate_form_legal: "Os seus dados são tratados confidencialmente pela e2w Holding / SUNCOM Estate.<br>Sem partilha com terceiros. Resposta garantida em 48h.",
    estate_success_title: "Candidatura recebida",
    estate_success_sub: "Obrigado. O seu perfil está a ser analisado.<br>William Legendre entrará em contacto em 48h.",
    estate_footer: "e2w Holding — © 2026 — Confidencial",

  },

  ru: {
    nav_cta: "Присоединиться",
    hero_eyebrow: "Агенты по недвижимости & Со-акционеры",
    hero_sub: "Будущее недвижимости пишется здесь",
    hero_scroll: "Открыть",
    b1_tag: "Агенты & Акционеры",
    b1_desc: "Как независимый агент по недвижимости, вы становитесь партнёром & акционером! Вы получаете комиссионные, делите прибыль; у вас есть реальный капитал и передаваемые активы.<br><span style=\"color:#ffffff;\">Постройте своё будущее!</span>",
    b1_link: "Стать агентом-основателем",
    b2_tag: "100% Услуги по недвижимости",
    b2_desc: "Вашим клиентам нужно финансирование, оценка, бассейн, пристройка, ландшафтный дизайн? Присоединяйтесь к нашим 52K агентам и получите «<span style=\"font-size:0.85em;\">PASS FACILITIES</span>» с нашими 30K партнёрами.<br><span style=\"color:#ffffff;\">Больше комиссий, больше прибыли!</span>",
    b2_link: "Узнать больше",
    b3_tag: "Клуб",
    b3_desc: "Обменивайтесь опытом с коллегами и партнёрами в нашем частном клубе. Открывайте новейшие инструменты и выигрышные тактики. Управляйте всем бизнесом в одном приложении.<br><span style=\"color:#ffffff;\">Международное сообщество!</span>",
    b3_link: "Присоединиться к сети",
    b4_desc: "Участвуйте в исследованиях, присоединившись к нашему Think Tank в Нью-Йорке. Технологии, И.И., SaaS, видео, коммуникации, соцсети, бенчмарки… OPEN!<br><span style=\"color:#ffffff;\">Партнёр до 31.08.26 <span style=\"color:#F0A500;\">⌱</span> 1 перелёт в Нью-Йорк в подарок!</span>",
    b4_link: "Открыть Lab",
    footer_rights: "Все права защищены",
    about_eyebrow: "⌱ Группа SUNCOM",
    about_sub: "Юридическая и финансовая структура экосистемы SUNCOM.",
    e2w_label: "Юридический адрес",
    section_team: "Основатели & Партнёры",
    bio_read: "Читать биографию",
    bio_hide: "Скрыть биографию",
    erwan_role: "Основатель & Партнёр — Президент e2w · SUNCOM Associates",
    erwan_b1: "Серийный предприниматель на международном уровне с 1991 года — Недвижимость & Новые технологии",
    erwan_b2: "Основатель и руководитель компаний во Франции, Италии, Испании, Великобритании, Бахрейне...",
    erwan_b3: "До 300 сотрудников по всему миру — партнёрства с Canal+ / Air France / Iberia",
    erwan_history: "Немного истории",
    erwan_bio: "<p>Родился в 1966 году, после юности спортсмена высокого уровня провёл 3 года в университете на факультете иностранных языков, прежде чем понял — ему нужно действие!</p><p>На протяжении 35 лет создаёт, руководит и владеет долями в международных компаниях в сфере недвижимости и новых технологий. В партнёрстве с Canal Plus, Air France и Iberia имел собственный стенд в парижских аэропортах и личный авиалайнер для сопровождения клиентов.</p><p>Сейчас активно развивает проект SUNCOM вместе с давними партнёрами William & Wilfrid.</p>",
    william_role: "Основатель & Партнёр — Президент SUNCOM Facilities",
    william_b1: "Основатель и руководитель с 1999 года первой сети коммерческих агентов и фрилансеров",
    william_b2: "Лидер рынка 25 лет — 57 000 агентов — 30 000 компаний-клиентов",
    william_b3: "55 миллиардов евро годового оборота, генерируемого его командами",
    william_history: "Немного истории",
    william_bio: "<p>Продажи — его двигатель! Родился в 1975 году, основал платформу AgentCo более 25 лет назад и стал №1 в рекрутинге независимых коммерческих агентов во Франции, Бельгии и Люксембурге.</p><p>Он является пионером модели сетей независимых мандатариев и развил sourcing таких структур, как IAD и SAFTI, занимающих 27% французского рынка недвижимости.</p><p>Партнёр Wilfrid & Erwan в e2w, руководит SUNCOM Facilities, совмещая страсть к И.И. и автоматизации продаж.</p>",
    wilfrid_role: "Основатель & Партнёр — Президент SUNCOM Estate",
    wilfrid_b1: "Судебный исполнитель 18 лет — Франция & Канада",
    wilfrid_b2: "Агент по недвижимости 15 лет — сотрудничает с двадцатью агентствами во Франции",
    wilfrid_b3: "Постоянный преподаватель для адвокатов коллегии Квебека в течение 3 лет",
    wilfrid_history: "Немного истории",
    wilfrid_bio: "<p>Родился в 1965 году, почти 20 лет проработал судебным исполнителем во Франции и заморских территориях. Позднее увлёкся недвижимостью и сегодня сотрудничает с двадцатью агентствами во Франции.</p><p>Проект e2w точно отражает его желание продвигать инновации через амбициозный международный проект. Партнёр Erwan & William, руководит SUNCOM Estate.</p><p class=\"bio-quote\">« В смелости есть гений, сила и магия » — Гёте</p>",
    legal_title: "Правовая информация",
    legal_editor: "Издатель",
    legal_host: "Хостинг",
    legal_ip: "Интеллектуальная собственность",
    legal_ip_text: "Все материалы сайта (тексты, визуалы, архитектура) являются исключительной собственностью e2w Holding и её дочерних компаний SUNCOM. Любое воспроизведение, даже частичное, запрещено без предварительного письменного разрешения.",
    legal_data: "Персональные данные",
    legal_data_text: "Сайт не собирает персональные данные без явного согласия. В соответствии с GDPR вы имеете право на доступ, исправление и удаление ваших данных. Контакт: contact-e2w@pm.me",
    legal_cookies: "Куки",
    legal_cookies_text: "Сайт использует только функциональные куки (настройка темы). Рекламные или сторонние куки отслеживания не используются.",
    back_home: "← Главная",
    buyest_cta: "Смотреть объявления",
    // suncom_landing_estate.html
    estate_back: "Назад",
    estate_label: "SUNCOM Estate — Агенты & Акционеры",
    estate_h1: "Хватит обогащать<br><em>других.</em><br><span class=\"line-amber\">Стань владельцем</span><br>ценности, которую ты создаёшь.",
    estate_intro1: "<strong style=\"color:#ffffff;\">SUNCOM Estate</strong> — не просто ещё одна риэлторская сеть.<br><br>Это единственная модель, где независимые агенты умножают источники дохода, входят в капитал, получают комиссии и делят прибыль — не жертвуя свободой.<br><br>Всё остальное даёт тебе лишь визитку, инструменты и обучение, доступные любому. Серьёзно?",
    estate_quote1: "100% ценности агентства — <strong style=\"font-size:1.35em;\">это ты</strong> 🫵!",
    estate_q2_title: "Продаёшь — живёшь; не продаёшь — конец!",
    estate_q2_body: "Не с <strong style=\"color:#ffffff;\">SUNCOM Estate</strong> — всегда есть платные услуги, даже в периоды спада. Ты — единственный человек, который имеет значение!",
    estate_stat1: "опыта",
    estate_stat2: "Реальные акции с первого дня",
    estate_stat3: "Коммерческих агентов",
    estate_hero_cta: "Хочу присоединиться",
    estate_args_label: "Что меняет всё",
    estate_a1_title: "Соакционер",
    estate_a1_desc: "Ты входишь в капитал SUNCOM Estate через BSA. Твои продажи повышают стоимость компании, которой ты владеешь — не инвестфонда. Ноль риска; весь профит.",
    estate_a2_title: "Несколько комиссий",
    estate_a2_desc: "75% для всех, точка. Плюс зарабатываешь на кредитах, диагностике, ремонте, бассейнах, переездах… А в конце года все летят в Нью-Йорк на вручение дивидендов!",
    estate_a3_title: "Правовая защита",
    estate_a3_desc: "Эксклюзивное партнёрство с FIDAL во Франции и международно. Защита интересов компании и агентов-акционеров. Юридическая фирма №1 во Франции.",
    estate_a4_title: "Инструменты, технологии и ИИ",
    estate_a4_desc: "Все каналы продвижения, предиктивный поиск клиентов, виртуальные агенты, чат-бот, многоязычная CRM, SaaS, мультиплатформенные API…",
    estate_a5_title: "Сеть опытных основателей",
    estate_a5_desc: "Erwan Milbéo (35 лет в международной недвижимости), Wilfrid Meyer (судебный пристав, 60 агентств), William Legendre (основатель AgentCo, запустил IAD & SAFTI).",
    estate_a6_title: "Международный масштаб",
    estate_a6_desc: "Быстро масштабироваться вместе и по всему миру. Цель — IPO. Активная R&D в SUNCOM Lab в Нью-Йорке — ты скоро получишь приглашение за счёт SUNCOM!",
    estate_form_label: "Заявка агента & партнёра",
    estate_form_title: "Присоединиться к <span>SUNCOM</span><br>Estate",
    estate_form_sub: "10 вопросов · Профиль проверен за 48ч · Встреча с основателями",
    estate_form_timer: "2 минуты",
    estate_bloc1: "01 — Личные данные",
    estate_bloc2: "02 — Текущая ситуация",
    estate_bloc3: "03 — Мотивация",
    estate_bloc4: "04 — Доступность",
    estate_submit: "Отправить заявку",
    estate_form_legal: "Ваши данные обрабатываются конфиденциально e2w Holding / SUNCOM Estate.<br>Без передачи третьим лицам. Ответ гарантирован в течение 48ч.",
    estate_success_title: "Заявка получена",
    estate_success_sub: "Спасибо. Ваш профиль анализируется.<br>William Legendre свяжется с вами в течение 48ч.",
    estate_footer: "e2w Holding — © 2026 — Конфиденциально",

  }
};

const LANG_META = {
  fr: { flag: '🇫🇷', label: 'Français' },
  en: { flag: '🇬🇧', label: 'English' },
  de: { flag: '🇩🇪', label: 'Deutsch' },
  es: { flag: '🇪🇸', label: 'Español' },
  pt: { flag: '🇵🇹', label: 'Português' },
  ru: { flag: '🇷🇺', label: 'Русский' },
};

function applyLang(lang) {
  const t = SUNCOM_LANGS[lang] || SUNCOM_LANGS['fr'];
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    // Les boutons bio utilisent bio_read/bio_hide selon leur état
    if (el.classList && el.classList.contains('bio-toggle')) {
      el.textContent = el.classList.contains('open') ? (t.bio_hide || t[key]) : (t.bio_read || t[key]);
      return;
    }
    if (t[key] !== undefined) el.textContent = t[key];
  });
  document.querySelectorAll('[data-i18n-html]').forEach(el => {
    const key = el.getAttribute('data-i18n-html');
    if (t[key] !== undefined) el.innerHTML = t[key];
  });
  // Mettre à jour le sélecteur
  const btn = document.getElementById('langBtn');
  if (btn) btn.textContent = LANG_META[lang].flag + ' ' + lang.toUpperCase() + ' ▾';
  localStorage.setItem('suncom_lang', lang);
  document.documentElement.lang = lang;
}

function initLangSelector() {
  const container = document.getElementById('langSelector');
  if (!container) return;

  const saved = localStorage.getItem('suncom_lang') || 'fr';

  // Bouton
  const btn = document.createElement('button');
  btn.id = 'langBtn';
  btn.className = 'theme-toggle';
  btn.style.cssText = 'min-width:90px;justify-content:center;';
  btn.textContent = LANG_META[saved].flag + ' ' + saved.toUpperCase() + ' ▾';

  // Dropdown
  const dropdown = document.createElement('div');
  dropdown.id = 'langDropdown';
  dropdown.style.cssText = 'display:none;position:absolute;top:calc(100% + 8px);right:0;background:var(--bg-nav);border:1px solid var(--border);border-radius:8px;padding:6px;min-width:160px;z-index:200;backdrop-filter:blur(12px);';

  Object.entries(LANG_META).forEach(([code, meta]) => {
    const item = document.createElement('button');
    item.style.cssText = 'display:flex;align-items:center;gap:8px;width:100%;padding:7px 12px;background:none;border:none;cursor:pointer;color:var(--text);font-size:12px;letter-spacing:0.05em;border-radius:4px;font-family:DM Sans,sans-serif;transition:background 0.15s;text-align:left;';
    item.innerHTML = `<span>${meta.flag}</span><span>${meta.label}</span>`;
    item.onmouseenter = () => item.style.background = 'rgba(0,201,177,0.08)';
    item.onmouseleave = () => item.style.background = 'none';
    item.onclick = () => {
      applyLang(code);
      dropdown.style.display = 'none';
    };
    dropdown.appendChild(item);
  });

  container.style.position = 'relative';
  container.appendChild(btn);
  container.appendChild(dropdown);

  btn.onclick = (e) => {
    e.stopPropagation();
    dropdown.style.display = dropdown.style.display === 'none' ? 'block' : 'none';
  };
  document.addEventListener('click', () => dropdown.style.display = 'none');

  applyLang(saved);
}

if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', initLangSelector);
} else {
  initLangSelector();
}
